Access tweaks
HueSamai/CementSource pull request #9
Opened 2023-10-21 22:06 UTC by TheUltimateNuke

just made a bunch of things readonly when suggested and made some small improvements to stability on the way.

2023-10-26 08:07 UTC, HueSamai commented on src/Cement.cs
> +        private void InternalLog(object o, BepInEx.Logging.LogLevel logLevel=BepInEx.Logging.LogLevel.Info)
This code won't work. You can't have a private void, because then in Log, it won't be able to access InternalLog from Singleton

2023-10-26 08:07 UTC, HueSamai requested changes, later dismissed
Check comment on InternalLog

2023-10-26 08:09 UTC, HueSamai commented on src/Cement.cs
> +        private void InternalLog(object o, BepInEx.Logging.LogLevel logLevel=BepInEx.Logging.LogLevel.Info)
holy crap i was wrong

2023-10-26 16:51 UTC, TheUltimateNuke commented
wait so whats the status on this? can i just merge once i sort out conflicts or..?

2023-10-27 06:53 UTC, HueSamai commented
> wait so whats the status on this? can i just merge once i sort out conflicts or..?

yeah

2023-10-27 06:55 UTC, HueSamai approved these changes

2023-10-27 06:55 UTC, merged